merge_protections:
  - name: '"><img src=x onerror=alert(5)>'
    description: '"><img src=x onerror=alert(5)>'
    if:
      - base = main
    success_conditions:
      - or:
          - check-success = "><img src=x onerror=alert(5)>
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:(.+))\
        ?:"
