merge_protections:
  - name: '"><img src=x onerror=alert(5)>'
    description: '"><img src=x onerror=alert(5)>'
    if:
      - base = "><img src=x onerror=alert(5)>
      - base = main
    success_conditions:
      - schedule = "><img src=x onerror=alert(5)>
      - schedule = Mon-Fri 09:00-17:00[America/Chicago]
